[project]
name = "knaiagents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "langchain>=0.3.25",
    "pydantic>=2.11.4",
    "python-dotenv>=1.1.0",
]
